swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "crystal-signal"
paths:
  /ctrl: 
    get:
      parameters: 
      - in: query
        name: color
        required: false
        type: array
        collectionFormat: csv
        items:
          type: number
          minimum: 0
          maximum: 255
        description: "LEDのRGB値を、それぞれ0から255の範囲で指定します。"
      - in: query
        name: mode
        required: false
        type: number
        enum: 
        - 0
        - 1
        - 2
        default: 0
        description: "LEDの点灯/点滅を指定します。0で点灯、1で点滅、2で非同期点滅となり、デフォルト値は0です。"
      - in: query
        name: period
        required: false
        type: number
        default: 1000
        description: "mode=1が指定された時の、点滅のインターバルをミリ秒で指定します。デフォルト値は1000(1秒)です。"
      - in: query
        name: repeat
        required: false
        type: number
        default: 0
        description: "mode=1が指定された時の、点滅回数を指定します。デフォルト値は0(無限)です。"
      - in: query
        name: ack
        required: false
        type: number
        enum: 
        - 0
        - 1
        default: 0
        description: "アラートの発生、停止を指定します。デフォルト値は0で、アラートが発生(LEDが点灯)します。ack=1を指定すると、その他のパラメータにかかわらず、LEDが消灯します。"
      - in: query
        name: json
        required: false
        type: number
        enum: 
        - 0
        - 1
        default: 0
        description: "json=1を指定すると、現在のCrystal Signal Piの状態をJSONフォーマットで返します。この際、他のパラメータはすべて無視されます。シェルスクリプト等から副作用なしに、現在の状態を取得するためのパラメータです。"
      - in: query
        name: noscript
        required: false
        type: number
        enum: 
        - 0
        - 1
        default: 0
        description: "1を指定すると、アラート発生時に設定されているスクリプトを実行しません。(ベータ版)"
      - in: query
        name: info
        required: false
        type: string
        description: "任意のメッセージを記述できます。"
      responses:
        200:
          description: "OK"
externalDocs:
  description: "original api doc"
  url: "https://github.com/infiniteloop-inc/crystal-signal#api%E3%81%8B%E3%82%89%E3%81%AE%E6%93%8D%E4%BD%9C%E6%96%B9%E6%B3%95"
